//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia_Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agencia_Viaje()
        {
            this.Contrato_Agencia = new HashSet<Contrato_Agencia>();
            this.Venta_Pasajes = new HashSet<Venta_Pasajes>();
        }
    
        public int id_Agencia_Viaje { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<int> num_Documento { get; set; }
        public string direccion { get; set; }
        public string urbanizacontratocion { get; set; }
        public string Representante_Legal { get; set; }
        public Nullable<int> telefono { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_Ubigeo { get; set; }
        public Nullable<int> id_Tipo_Documento { get; set; }
    
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Agencia> Contrato_Agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Pasajes> Venta_Pasajes { get; set; }
    }
}
