//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.Asiento = new HashSet<Asiento>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
            this.Programacion_vuelo = new HashSet<Programacion_vuelo>();
            this.Reg_Cambios_Vuelo = new HashSet<Reg_Cambios_Vuelo>();
            this.Registro_Avion_ASAP = new HashSet<Registro_Avion_ASAP>();
            this.Urt_Asap = new HashSet<Urt_Asap>();
        }
    
        public int id_Avion { get; set; }
        public string Nomb_FAbricante { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string numero_placa { get; set; }
        public Nullable<int> cantidad_pasajeros { get; set; }
        public Nullable<int> numero_motores { get; set; }
        public string sistema_seguridad { get; set; }
        public Nullable<System.DateTime> Fecha_fabricacion { get; set; }
        public Nullable<decimal> peso_bruto { get; set; }
        public Nullable<decimal> peso_neto { get; set; }
        public string estado { get; set; }
        public Nullable<System.TimeSpan> Tiempo_recorrido { get; set; }
        public Nullable<int> id_Aerolinea { get; set; }
        public Nullable<int> id_Servicio { get; set; }
        public Nullable<int> id_Contrato_Alquiler { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Contrato_Alquiler Contrato_Alquiler { get; set; }
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programacion_vuelo> Programacion_vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reg_Cambios_Vuelo> Reg_Cambios_Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Avion_ASAP> Registro_Avion_ASAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urt_Asap> Urt_Asap { get; set; }
    }
}
