//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprobante_Venta()
        {
            this.Reg_Cambios_Venta_vuelo = new HashSet<Reg_Cambios_Venta_vuelo>();
        }
    
        public int Id_comprobante { get; set; }
        public string Nom_aerolinea { get; set; }
        public Nullable<System.DateTime> Fecha_Vuelo { get; set; }
        public Nullable<System.DateTime> Hora_Vuelo { get; set; }
        public Nullable<int> Puerta_embarque { get; set; }
        public string estado { get; set; }
        public Nullable<int> Id_venta_pasaje { get; set; }
        public Nullable<int> Cod_unico_ticket { get; set; }
    
        public virtual Venta_Pasajes Venta_Pasajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reg_Cambios_Venta_vuelo> Reg_Cambios_Venta_vuelo { get; set; }
    }
}
