//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Empleado
    {
        public int Id_contrato_emp { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string estado { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_area { get; set; }
        public Nullable<int> Id_rol { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
