//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Servicio
    {
        public int Id_Det_Servicio { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string estado_actividad { get; set; }
        public Nullable<int> id_Aerolinea { get; set; }
        public Nullable<int> id_Servicio { get; set; }
        public Nullable<int> id_Empleado { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
