//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsapEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Venta
    {
        public int Id_Det_Venta { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public string tip_moneda { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> precio_descuento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string estado_actividad { get; set; }
        public Nullable<int> Id_venta_pasaje { get; set; }
        public Nullable<int> Id_Progra_Vuelo { get; set; }
        public Nullable<int> id_Empleado_Responsable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Programacion_vuelo Programacion_vuelo { get; set; }
        public virtual Venta_Pasajes Venta_Pasajes { get; set; }
    }
}
