//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion_Operar
    {
        public int id_Autorizacion_Operar { get; set; }
        public Nullable<System.DateTime> fecha_Ini_operacion { get; set; }
        public Nullable<System.DateTime> fecha_Fin_operacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_Reg_Avion_ASAP { get; set; }
        public Nullable<int> id_Permiso_Operacion { get; set; }
    
        public virtual Permiso_Operacion Permiso_Operacion { get; set; }
        public virtual Registro_Avion_ASAP Registro_Avion_ASAP { get; set; }
    }
}
