//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Contrato_Alquiler
    {
        public int Id_Det_Contrato_Alquiler { get; set; }
        public string Num_placa_avion { get; set; }
        public Nullable<System.DateTime> fecha_Ini_Alquiler { get; set; }
        public Nullable<System.DateTime> fecha_Fin_Alquiler { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string estado_actividad { get; set; }
        public Nullable<int> id_Contrato_Alquiler { get; set; }
        public Nullable<int> id_Empleado { get; set; }
    
        public virtual Contrato_Alquiler Contrato_Alquiler { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
