//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_repuesto
    {
        public int Id_Det_repuesto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string estado_actividad { get; set; }
        public Nullable<int> id_repuesto { get; set; }
        public Nullable<int> Id_mantenimiento { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
        public virtual Repuestos Repuestos { get; set; }
    }
}
