//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimiento()
        {
            this.Det_Diagnostico = new HashSet<Det_Diagnostico>();
            this.Det_repuesto = new HashSet<Det_repuesto>();
        }
    
        public int Id_mantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha_mant { get; set; }
        public string Estado { get; set; }
        public string Tipo_mant { get; set; }
        public Nullable<int> Id_avion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_prove_mant { get; set; }
    
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Diagnostico> Det_Diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_repuesto> Det_repuesto { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Proveedor_Mantenimiento Proveedor_Mantenimiento { get; set; }
    }
}
