//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_Alq_Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor_Alq_Avion()
        {
            this.Contrato_Alquiler = new HashSet<Contrato_Alquiler>();
        }
    
        public int id_Provee_Alq_Avion { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<int> num_Documento { get; set; }
        public string direccion { get; set; }
        public string urbanizacion { get; set; }
        public string Representante_Legal { get; set; }
        public Nullable<int> telefono { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_Ubigeo { get; set; }
        public Nullable<int> id_Tipo_Documento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Alquiler> Contrato_Alquiler { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
